# Definition of the Conda Environment.
#
# WARNING: Only the required packages are in the environment.
#          The following optional libraries are not installed:
#              - Jupyter and Trame
#              - CuPy, FFTW, UMFPACK, and MKL/PARDISO
#
# (c) Thomas Guillod - Dartmouth College

name: PyPEEC
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyyaml=6.0
  - numpy=1.24.1
  - scipy=1.9.3
  - matplotlib=3.6.2
  - pillow=9.4.0
  - vtk=9.2.5
  - pyvista=0.38.3
  - pyvistaqt=0.9.1
  - qtpy=2.3.0
  - pyqt=5.15.7
