# Definition of the Conda Development Environment.
#
# WARNING: Install all the PyPEEC dependencies.
#          The optional libraries are included.
#          The packaging/development tools are included.
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

name: pypeec
channels:
  - conda-forge
  - defaults
dependencies:
  # base installation
  - python=3.10
  # dev tools
  - pip=23.1.2
  - twine=4.0.2
  - python-build=0.10.0
  - setuptools_scm=7.1.0
  - sphinx_rtd_theme=1.2.2
  - sphinx=6.2.1
  # YAML parsing library
  - pyyaml=6.0
  # numerical libraries
  - numpy=1.24.1
  - scipy=1.9.3
  - joblib=1.3.0
  # Qt bindings
  - pyqt=5.15.7
  # geometry manipulation and plotting libraries
  - vtk=9.2.6
  - pyvista=0.40.0
  - pyvistaqt=0.11.0
  - matplotlib=3.7.1
  - shapely=2.0.1
  - rasterio=1.3.8
  - pillow=10.0.0
  # optional Jupyter libs
  - jupyterlab=4.0.4
  - ipywidgets=8.1.0
  - trame=3.1.0
  # optional HPC libs
  - pyamg=5.0.1
  - cupy=12.1.0
  - scikit-umfpack=0.3.3
  # optional HPC toolkits
  - mkl-devel
  - cudatoolkit
  # optional HPC libs from PyPi
  - pip:
    - pyFFTW==0.13.1
    - pydiso==0.0.3
