# Definition of the Conda Development Environment.
#
# WARNING: Only tested with Linux x86/x64/glibc.
#
# WARNING: Install all the PyPEEC dependencies.
#          The optional libraries are included.
#          The packaging/development tools are included.
#
# WARNING: Some listed packages are NOT open source.
#          INTEL/MKL is not open source.
#          NVIDIA/CUDA is not open source.
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

name: pypeec
channels: [conda-forge]
dependencies:
  # base installation
  - python=3.11
  # dev tools
  - pip=24.3.1
  - twine=5.1.1
  - coverage=7.6.8
  - setuptools_scm=8.1.0
  - sphinx_rtd_theme=3.0.1
  - sphinx=8.1.3
  - pkg-config=0.29.2
  - python-build=1.2.2
  # logging and serialization
  - scilogger=1.2.2
  - scisave=1.4.1
  - jsonschema=4.23.0
  # numerical libraries
  - numpy=2.1.3
  - scipy=1.14.1
  - joblib=1.4.2
  # geometry libraries
  - vtk=9.3.1
  - pyvista=0.44.2
  - shapely=2.0.6
  - rasterio=1.4.2
  - pillow=11.0.0
  - matplotlib-base=3.9.2
  # interface libraries
  - pyqt=5.15.9
  - pyvistaqt=0.11.1
  # optional packages for Jupyter
  - jupyterlab=4.3.1
  - jupyter-server-proxy=4.4.0
  - ipywidgets=8.1.5
  - trame-vtk=2.8.12
  - trame-vuetify=2.7.2
  - trame=3.7.0
  - ipympl=0.9.4
  # optional optimized numerical libraries
  - pyamg=5.2.1
  - cupy=13.3.0
  - pyfftw=0.15.0
  - pydiso=0.1.2
  - mkl_fft=1.3.11
  # optional optimized numerical toolkits
  - mkl-devel=2024.2.2
  - cudatoolkit=11.8.0
