# Definition of the Conda Environment for PyPEEC.
#
# WARNING: Only the required packages are in the environment.
#          The following optional libraries are not installed:
#              - Jupyter, Notebook, and Trame
#              - FFTW, UMFPACK, and MKL/PARDISO
#              - CuPy and CUDA
#
# (c) Thomas Guillod - Dartmouth College

name: pypeec
channels:
  - conda-forge
  - defaults
dependencies:
  # base installation
  - python=3.10
  # YAML parsing library
  - pyyaml=6.0
  # numerical libraries
  - numpy=1.24.1
  - scipy=1.9.3
  - joblib=1.2.0
  # Qt bindings
  - pyqt=5.15.7
  # geometry manipulation and plotting libraries
  - vtk=9.2.5
  - pyvista=0.38.3
  - pyvistaqt=0.9.1
  - matplotlib=3.6.2
  - shapely=2.0.1
  - rasterio=1.3.6
  - pillow=9.4.0
