# Definition of the Conda Development Environment.
#
# WARNING: Only tested with Linux x86/x64/X11/glibc.
#
# WARNING: Install all the PyPEEC dependencies.
#          The optional libraries (HPC, GPU, and Jupyter) are included.
#          The packaging and development tools are also included.
#
# WARNING: Some listed packages are NOT open source.
#          INTEL/MKL is not open source.
#          NVIDIA/CUDA is not open source.
#
# WARNING: Some listed packages are under a copyleft license.
#          Qt is under a copyleft license (LGPL and GPL).
#          FFTW is also under a copyleft license (GPL).
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

name: pypeec
channels: [conda-forge]
dependencies:
  # base installation
  - python=3.13.9
  # dev tools
  - pip=25.3
  - ruff=0.14.5
  - twine=6.2.0
  - coverage=7.12.0
  - setuptools_scm=9.2.2
  - sphinx_rtd_theme=3.0.2
  - sphinx=8.2.3
  - pkg-config=0.29.2
  - python-build=1.3.0
  # logging and serialization
  - scilogger=1.2.5
  - scisave=1.6.0
  # numerical libraries
  - numpy=2.3.5
  - scipy=1.16.3
  - joblib=1.5.2
  # geometry libraries
  - vtk=9.5.2
  - pyvista=0.46.4
  - shapely=2.1.2
  - rasterio=1.4.3
  - pillow=12.0.0
  - matplotlib-base=3.10.8
  # interface libraries
  - qtpy=2.4.3
  - pyside6=6.9.3
  - pyvistaqt=0.11.3
  # optional packages for Jupyter
  - jupyterlab=4.5.0
  - ipython=9.7.0
  # optional optimized numerical libraries
  - pyamg=5.3.0
  - cupy=13.6.0
  - pyfftw=0.15.1
  - pydiso=0.2.0
  - mkl_fft=2.0.0
  - mkl-devel=2024.2.2
