# Definition of the Conda Environment for PyPEEC.
#
# WARNING: Only the required packages are in the environment.
#          The following optional libraries are not installed:
#              - FFTW, UMFPACK, PyAMG, and MKL/PARDISO
#              - Jupyter, IPyWidgets, and Trame
#              - CuPy and CUDA
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

name: pypeec
channels:
  - conda-forge
  - defaults
dependencies:
  # base installation
  - python=3.10
  # YAML parsing library
  - pyyaml=6.0
  # numerical libraries
  - numpy=1.24.1
  - scipy=1.9.3
  - joblib=1.3.0
  # Qt bindings
  - pyqt=5.15.7
  # geometry manipulation and plotting libraries
  - vtk=9.2.6
  - pyvista=0.40.0
  - pyvistaqt=0.11.0
  - matplotlib=3.7.1
  - shapely=2.0.1
  - rasterio=1.3.8
  - pillow=10.0.0
