# Definition of the Conda Environment.
#
# (c) Thomas Guillod - Dartmouth College

name: PyPEEC
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pyyaml=6.0
  - numpy=1.24.1
  - scipy=1.9.3
  - scikit-umfpack=0.3.3
  - pyfftw=0.13.1
  - matplotlib=3.6.2
  - pillow=9.4.0
  - vtk=9.2.5
  - pyvista=0.37.0
  - pyvistaqt=0.9.0
  - qtpy=2.3.0
  - pyqt=5.15.7
