# PyPEEC options for the 3D plots (using PyVista).
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

# options for defining cut planes
"plot_clip":
    "clip_plot": false                 # add (or not) a widget for interactive clipping
    "clip_invert": false               # invert (or not) the clipping direction
    "clip_axis": "z"                   # normal of the clipping direction
    "clip_value": 0.0                  # initial position for the clipping

# theme of the figure
"plot_theme":
    "text_color": "black"              # color of the text elements
    "title_font": 10                   # font size of the text displayed on the window corner
    "colorbar_font": 15                # font size of the color bar
    "colorbar_size": 5                 # number of division for the colorbar
    "colorbar_plot": true              # show (or not) the colorbar
    "background_color": "gray"         # background color of the plot
    "axis_add": true                   # add (or not) the axis marker
    "axis_size": 2                     # size of the axis marker

# options controlling the view rendering
"plot_view":
    "grid_plot": false                 # plot (or not) the complete voxel geometry as wireframe
    "grid_thickness": 1.0              # line thickness for the complete voxel geometry
    "grid_color": "black"              # line opacity for the complete voxel geometry
    "grid_opacity": 0.1                # line color for the complete voxel geometry
    "geom_plot": true                  # plot (or not) the non-empty voxels as wireframe
    "geom_thickness": 1.0              # line thickness for the non-empty voxels
    "geom_color": "black"              # line color for the non-empty voxels
    "geom_opacity": 0.1                # line opacity for the non-empty voxels
    "point_plot": true                 # plot (or not) the provided point cloud as dots
    "point_color": "red"               # color of the point cloud dots
    "point_size": 8.0                  # size of the point cloud dots
    "point_opacity": 0.5               # opacity of the point cloud dots
    "camera_roll": null                # camera roll angle (null for default)
    "camera_azimuth": null             # camera azimuth angle (null for default)
    "camera_elevation": null           # camera elevation angle (null for default)
