"domain":
    "framework": "pyvista"
    "plot_title": "Domain"
    "plot_type": "domain"
    "data_window": !include cfg_data_window.yaml
    "data_options": !include cfg_data_pyvista.yaml
    "data_plot":
        "title": "Domain"
        "colormap": "Accent"
        "opacity": 1.0
"connection":
    "framework": "pyvista"
    "plot_title": "Connection"
    "plot_type": "connection"
    "data_window": !include cfg_data_window.yaml
    "data_options": !include cfg_data_pyvista.yaml
    "data_plot":
        "title": "Connection"
        "colormap": "Accent"
        "opacity": 1.0
"voxelization":
    "framework": "pyvista"
    "plot_title": "Voxelization"
    "plot_type": "voxelization"
    "data_window": !include cfg_data_window.yaml
    "data_options": !include cfg_data_pyvista.yaml
    "data_plot":
        "title": "Voxelization"
        "color_voxel": "red"
        "color_reference": "blue"
        "opacity_voxel": 0.5
        "opacity_reference": 0.5
