# Run the "Standard tests" with the following conditions.
#   - push (all)
#   - pull request
#   - dispatch
#
# The test are run on:
#   - Linux / Ubuntu
#   - Python 3.10
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

name: Run Standard Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run the tests
        shell: bash -el {0}
        run: |
          chmod +x scripts/run_tests.sh
          ./scripts/run_tests.sh
