# Run the "Conda tests" with the following conditions.
#   - dispatch
#   - weekly
#
# The test are run on:
#   - Linux / Ubuntu
#   - Python 3.10
#
# Two different kinds of tests are made:
#   - using the "conda_base.yaml" file
#   - using the "conda_dev.yaml" file
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

name: Run Conda Tests

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1"

jobs:
  default:
    strategy:
      fail-fast: false
      matrix:
        method:
          - name: "conda_base"
            cmd:  |
              conda env create --file conda_base.yaml
              conda activate pypeec
          - name: "conda_dev"
            cmd:  |
              conda env create --file conda_dev.yaml
              conda activate pypeec
          - name: "conda_forge"
            cmd:  |
              conda create --name pypeec python=3.10
              conda activate pypeec
              conda install conda-forge::pypeec
              conda remove --force --yes --quiet pypeec
    name: ${{ matrix.method.name }}
    runs-on: "ubuntu-latest"
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          use-mamba: true
      - name: Install dependencies
        shell: bash -el {0}
        run: ${{ matrix.method.cmd }}
      - name: Run the tests
        shell: bash -el {0}
        run: |
          conda activate pypeec
          chmod +x scripts/run_tests.sh
          ./scripts/run_tests.sh
