# Run the Conda tests with the following conditions.
#   - dispatch
#   - weekly
#
# The test are run on:
#   - Linux / Ubuntu
#   - Python 3.10
#
# Two different kinds of tests are made:
#   - using the "conda_base.yaml" file
#   - using the "conda_dev.yaml" file
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

name: Run Conda Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        conda:
          - name: "base"
            file: "conda_base.yaml"
          - name: "dev"
            file: "conda_dev.yaml"
        system: ["ubuntu-latest"]
        version: ["3.10"]

    name: Conda / ${{ matrix.conda.name }}
    runs-on: ${{ matrix.system }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.version }}
          auto-activate-base: false
          activate-environment: pypeec
          environment-file: ${{ matrix.conda.file }}
      - name: Run the tests
        shell: bash -el {0}
        run: |
          chmod +x scripts/run_tests.sh
          ./scripts/run_tests.sh
