# Run the tests after a manual trigger.
# The tests are run with different platforms with a single Python version.
#
# The environment variable "ALLOW_PLOTTING" is used to prevent warnings without display server.
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

name: Test Different Platforms

on: ["workflow_dispatch"]

env:
  ALLOW_PLOTTING: "true"
  PYTHONIOENCODING: "utf8"
  PYTHONUNBUFFERED: "1"

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os-type }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os-type: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python / ${{ matrix.os-type }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies  / ${{ matrix.os-type }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run the tests / ${{ matrix.os-type }}
        shell: bash
        run: |
          source run_tests.sh
