# Run the tests after each push/pull event.
# The tests are run with a single Python version.
#
# The environment variable "ALLOW_PLOTTING" is used to prevent warnings without display server.
#
# (c) Thomas Guillod - Dartmouth College

name: Tests (push/pull trigger)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  ALLOW_PLOTTING: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run the tests
      run: |
         source run_tests.sh
