# Run the Platform tests with the following conditions.
#   - dispatch
#   - weekly
#
# The test are run on:
#   - Linux / Ubuntu
#   - Apple / macOS
#   - Microsoft / Windows
#   - Python 3.9
#   - Python 3.10
#   - Python 3.11
#   - Python 3.12
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

name: Run Platform Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        method:
          - name: "requirements"
            cmd: "pip install -r requirements.txt"
          - name: "package"
            cmd: "pip install ."
        system: ["ubuntu-latest",  "macos-latest", "windows-latest"]
        version: ["3.9", "3.10", "3.11", "3.12"]

    name: Platform / ${{ matrix.method.name }} / ${{ matrix.system }} / ${{ matrix.version }}
    runs-on: ${{ matrix.system }}
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          ${{ matrix.method.cmd }}
      - name: Run the tests
        shell: bash -el {0}
        run:
          chmod +x scripts/run_tests.sh
          ./scripts/run_tests.sh
