# Run the standard tests (on Linux / default Python version).
#
# Run with the following conditions:
#   - push/pull
#   - dispatch
#   - daily
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

name: Run Standard Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run the tests
        shell: bash
        run: |
          source run_tests.sh
