# Run the tests with different platforms (default Python version).
#
# Run with the following conditions:
#   - dispatch
#   - weekly
#
# The environment variable "ALLOW_PLOTTING" is used to prevent warnings without display server.
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

name: Test Platforms

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1"

env:
  ALLOW_PLOTTING: "true"
  PYTHONIOENCODING: "utf8"
  PYTHONUNBUFFERED: "1"

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os-type }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os-type: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python / ${{ matrix.os-type }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies  / ${{ matrix.os-type }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run the tests / ${{ matrix.os-type }}
        shell: bash
        run: |
          source run_tests.sh
