# Run the standard tests (on Linux / default Python version).
#
# Run with the following conditions:
#   - push/pull
#   - dispatch
#   - daily
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

name: Run Standard Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        conda:
          - name: "base"
            file: "conda_base.yaml"
          - name: "dev"
            file: "conda_dev.yaml"
    name: OS ${{ matrix.matrix.name }}
    runs-on: "ubuntu-latest"
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          auto-activate-base: false
          activate-environment: pypeec
          environment-file: ${{ matrix.matrix.file }}
      - name: Run the tests
        shell: bash -el {0}
        run: |
          conda info
          chmod +x scripts/run_tests.sh
          ./scripts/run_tests.sh
