# Run the standard tests (on Linux / default Python version).
#
# Run with the following conditions:
#   - push/pull
#   - dispatch
#   - daily
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

name: Run Standard Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        method:
          - name: "requirements"
            cmd: "pip install -r requirements.txt"
          - name: "package"
            cmd: "pip install ."
    name: Standard / ${{ matrix.method.name }}
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          ${{ matrix.method.cmd }}
      - name: Run the tests
        shell: bash
        run: |
          chmod +x scripts/run_tests.sh
          ./scripts/run_tests.sh
