# Run the tests after each push/pull event.
# The tests are run with a single Python version on Linux.
#
# The environment variable "ALLOW_PLOTTING" is used to prevent warnings without display server.
#
# Thomas Guillod - Dartmouth College
# Mozilla Public License Version 2.0

name: Automated Tests

on:
  workflow_dispatch:
    branches: ["main"]
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  ALLOW_PLOTTING: "true"
  PYTHONIOENCODING: "utf8"
  PYTHONUNBUFFERED: "1"

permissions:
  contents: read

jobs:
  build:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run the tests
        shell: bash
        run: |
          source run_tests.sh
